-- MySQL Script generated by MySQL Workbench
-- Tue May  7 12:01:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LibraryManagingSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LibraryManagingSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LibraryManagingSystem` DEFAULT CHARACTER SET utf8mb4 ;
USE `LibraryManagingSystem` ;

-- -----------------------------------------------------
-- Table `LibraryManagingSystem`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryManagingSystem`.`Users` (
  `idUsers` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(80) NOT NULL,
  `Key` VARCHAR(45) NOT NULL,
  `IsAdmin` INT(11) NOT NULL,
  `Taxes` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `Key_UNIQUE` (`Key` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `LibraryManagingSystem`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LibraryManagingSystem`.`Books` (
  `idBooks` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Author` VARCHAR(100) NOT NULL,
  `Status` INT(11) NOT NULL,
  `returnDate` DATE NULL DEFAULT NULL,
  `TakenBy` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`idBooks`),
  INDEX `fk_Books_Users_idx` (`TakenBy` ASC) VISIBLE,
  CONSTRAINT `fk_Books_Users`
    FOREIGN KEY (`TakenBy`)
    REFERENCES `LibraryManagingSystem`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
